#!/usr/bin/env python3

import os
import requests
from collections import Counter
from ruamel.yaml import YAML

yaml = YAML(typ='safe')

with open(os.path.expanduser('~/.local/bin/files/secrets.yml')) as f:
    secrets = yaml.load(f)

auth = (secrets['agency_username'], secrets['agency_password'])

with open(os.path.expanduser('~/.local/bin/files/list_of_job_ids.csv')) as f:
    experiment_ids = f.read().splitlines()

for i in range(len(experiment_ids)):
    r = requests.get(
        'https://agency.f4.htw-berlin.de/cc/batches?experimentId={}'.format(experiment_ids[i]),
        auth=auth
    )
    r.raise_for_status()
    data = r.json()

    print(Counter([batch['state'] for batch in data]))
