#!/usr/bin/env python3
import sys
import os
import subprocess
from subprocess import check_output

def get_name_of_branch():
    out = check_output(["git", "branch"]).decode("utf8")
    current = next(line for line in out.split("\n") if line.startswith("*"))
    return current.strip("*").strip()

git_name_of_branch = get_name_of_branch()

commit_message = ' '.join(sys.argv[1:])


subprocess.call(['python','_create_new_dvc_file.py'])
subprocess.call(['git','add','-A'])
if commit_message is '':
    subprocess.call(['git','commit','-m', '"Build pipeline: '+git_name_of_branch+'"'])
else:
    subprocess.call(['git','commit','-m', '"'+commit_message+'"'])
subprocess.call(['git','push','--set-upstream', 'origin',git_name_of_branch])
subprocess.call(['hub','sync'])


