#!/usr/bin/env python3
import sys
import os
import subprocess
from subprocess import check_output

def get_name_of_branch():
    out = check_output(["git", "branch"]).decode("utf8")
    current = next(line for line in out.split("\n") if line.startswith("*"))
    return current.strip("*").strip()

git_name_of_branch = get_name_of_branch()

name_of_branch = sys.argv[1]

subprocess.call(['hub', 'sync'])
subprocess.call(['git', 'checkout', name_of_branch])
subprocess.call(['dvc', 'pull'])



